### PR TITLE
Update repos.json

### PR DESCRIPTION
**Pull request by jmcouffin**
added a couple of usual suspect in the python/pyrevit/Revit sphere

### CODE REVIEW

**Comment by gtalarico** [comment]
Thanks @jmcouffin 
Can you run `python update.py` to fetch repos content?
The contents must be included in the repo/pr in ordered to be indexed by apidocs.co

**Comment by jmcouffin** [comment]
> Thanks @jmcouffin Can you run `python update.py` to fetch repos content? The contents must be included in the repo/pr in ordered to be indexed by apidocs.co

@gtalarico 

I did
The folder creation work but the git / subprocess part of the update does not work on my system (vscode on win10) 
It seems it has to do with ssh auth. But I cannot figure out what setup will make it work in vscode
When Using git://github.com/user/repo.git in the repos address seems to work up to a point

Are you on a Mac? I am guessing the subprocess shell script is not the same.

**Comment by jmcouffin** [comment]
Hi @gtalarico , 
My findings: 
It had to do with the shell you are using vs mine. 

In mine, I couldn't store the passphrase for my SSH key, so I switch the list of repo to non SSH address. 
Handled in both cases I am guessing.

Also, some command were different, so I built a specific update script and added it to the repo.
The logic is different as it checks if theres a repos folder, deletes it, clone all the repos, then deletes irrelevant files and empty folder. Not the most elegant solution, but works just fine.


I hope this will help further collaborators to the apidocs website. This website helped me progress with coding so much, Thanks for that.

**Comment by jmcouffin** [comment]
> Thanks @jmcouffin Can you run `python update.py` to fetch repos content? The contents must be included in the repo/pr in ordered to be indexed by apidocs.co

hi @gtalarico if you get a chance to have a look 👍

**Comment by gtalarico** [comment]
Hey @jmcouffin 
I would prefer not to have two scripts. And I am not sure we need to sep. versions at this time since this is a pretty script. There should be a clean way to make a single script work for all platforms.

Also would be preferred to make any changes to `update.py` in sep. PR from adding new repos.(PR 1: update script; PR 2: Add new repos). Currently the PR is so large I can load and find the changes to script in the large diff

**Comment by jmcouffin** [comment]
Done, let me know if it is fine now.
I understand the will not to have 2 scripts. I don't mind, I just did mine to get things going as I could not make your script do what it was supposed to do whatever I tried.
I can keep my update.py script on the side in the meantime.

**Pull request closed without merging**
